name: nestcure
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  http: ^0.13.3
  provider: ^6.0.3
  url_launcher: ^6.0.9
  path_provider: ^2.0.11
  file_picker: ^4.0.4
  permission_handler: ^9.1.0 
  intl: ^0.18.0

  cupertino_icons: ^1.0.6
  survey_kit: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
